import { Project } from "@/types";

export const projects: Project[] = [
  {
    slug: "neuroportal",
    hero: {
      title: "The Neuroportal",
      background: "/images/projects/neuroportal/background.svg",
    },
    steps: [
      {
        blocks: [
          {
            type: "topic",
            title: "Description of the project",
            text: "We are constantly thinking—our brains are always active, never truly at rest. This got us thinking: what if we could capture those brainwaves, the very essence of our thoughts, and make them visible ? What if we could transform something so intangible into something we can see, touch, or even experience ?",
            topics: [
              "Art Installation",
              "Meditative Artwork",
              "Inspired by the japanesse culture",
            ],
          },
        ],
      },
      {
        blocks: [
          {
            type: "title",
            text: "First Step",
            position: "center",
          },
          {
            type: "text",
            text: "The EEG captures the frequency that changes in our brain and TouchDesigner maps those signals into the moving visuals you see on the screen. TouchDesigner allows us to connect with the EEG headset and translate the brainwave patterns particularly into visual forms.",
            position: "center",
          },
          {
            type: "custom",
            component: "floating-particles",
          },
        ],
      },
      {
        blocks: [
          {
            type: "title",
            text: "Second Step",
            position: "center",
          },
          {
            type: "text",
            text: "Next, we come to the physical aspect of the project: the construction of the door. The door plays an important part of the project as it serves as a metaphorical gateway, symbolizing the transition from ordinary consciousness into more focused and meditative state of mind and also as a canva to the artwork.",
            position: "center",
          },
          {
            type: "media",
            medias: [
              {
                src: "/images/projects/neuroportal/first-proto-neuro.svg",
                alt: "Door 1",
                width: 522,
                height: 578,
              },
              {
                src: "/images/projects/neuroportal/second-proto-neuro.svg",
                alt: "Door 2",
                width: 562,
                height: 582,
              },
            ],
            mediasLayout: "grid",
          },
        ],
      },
      {
        blocks: [
          {
            type: "column",
            text: [
              "The opening of the door reflects the act of entering the visual space that will open to opportunity for inner reflection and reconnection.",
              "We wanted to place the door in a real-life setting, where it could offer a warm and inviting welcome.\n\nThanks to the AI-generated image, the prototype now lives in a realistic environment, drawing the viewer into its textures, waves, and soft tones that highlight the essence of the door.",
            ],
          },
          {
            type: "title",
            text: "Third Step",
            position: "center",
          },
          {
            type: "text",
            text: "Projection mapping allows us to project visuals onto a three-dimensional surface in this case, the door creating the illusion of depth and transformation. The visuals that are generated by the EEG data will be projected onto the door to create an ever-changing art piece. However, there have been some challenges with fitting the size of the projection to match the door perfectly.",
            position: "center",
          },
          {
            type: "media",
            medias: [
              {
                src: "/images/projects/neuroportal/third-step.svg",
                alt: "Third step",
                width: 1001,
                height: 456,
              },
            ],
            mediasLayout: "full-width",
          },
          {
            type: "media",
            medias: [
              {
                src: "/images/projects/neuroportal/portal-4.svg",
                alt: "Portal 4",
                width: 515,
                height: 687,
              },
              {
                src: "/images/projects/neuroportal/portal-5.svg",
                alt: "Portal 5",
                width: 522,
                height: 696,
              },
            ],
            mediasLayout: "grid",
          },
        ],
      },
      {
        blocks: [
          {
            type: "title",
            text: "Photos of the project",
          },
          {
            type: "media",
            medias: [
              {
                src: "/images/projects/neuroportal/portal-1.svg",
                alt: "Portal 1",
                width: 502,
                height: 707,
                className: "aspect-square object-cover",
              },
              {
                src: "/images/projects/neuroportal/portal-2.svg",
                alt: "Portal 2",
                width: 530,
                height: 719,
                className: "aspect-square object-cover",
              },
              {
                src: "/images/projects/neuroportal/portal-3.svg",
                alt: "Portal 3",
                width: 322,
                height: 707,
                className: "aspect-square object-cover",
              },
            ],
            mediasLayout: "grid",
          },
          {
            type: "media",
            medias: [
              {
                src: "/images/projects/neuroportal/festival-learning.jpg",
                alt: "Festival Learning",
                width: 3024,
                height: 4032,
                className: "aspect-square object-cover",
              },
              {
                src: "/images/projects/neuroportal/neuro-door.jpg",
                alt: "Neuro door",
                width: 3024,
                height: 4032,
                className: "aspect-square object-cover",
              },
              {
                src: "/images/projects/neuroportal/neuro-purple.jpg",
                alt: "Purple waves",
                width: 585,
                height: 923,
                className: "aspect-square object-cover",
              },
            ],
            mediasLayout: "grid",
          },
        ],
      },
    ],
  },
  {
    slug: "elastup",
    hero: {
      title: "Elastup",
      subtitle: "A multifunctional elastic band turned fashionable",
      background: "/images/projects/elastup/background.svg",
    },
    steps: [
      {
        blocks: [
          {
            type: "topic",
            title: "Description of the product",
            text: "The Elastup is a versatile and stylish accessory designed to tackle everyday challenges. Combining a durable elastic band with croûte de veau leather, this innovative product features horizontal slots that securely hold pens, cutlery, and other small essentials.",
            topics: [
              "Business project",
              "Multifunctional elastic",
              "A fashion item",
            ],
          },
          {
            type: "media",
            medias: [
              {
                src: "/images/projects/elastup/elastup-group-2.svg",
                alt: "Elastup Showcase",
                width: 2000,
                height: 800,
              },
            ],
            mediasLayout: "full-width",
          },
        ],
      },
      {
        blocks: [
          {
            type: "title",
            text: "Design Process",
          },
          {
            type: "text",
            text: "After several long brainstorming sessions without success, our idea finally came when a team member arrived with a tupperware held together by an elastic band — a simple workaround that inspired the project.\n\nWe came up with the idea of a stylish cutlery holder for tupperware, using a wider elastic band for better stability and a leather finish for elegance. Soon, the concept expanded to notebooks, iPads, and more — that is how Elastup was born.",
          },
          {
            type: "media",
            medias: [
              {
                src: "/images/projects/elastup/design-process.svg",
                alt: "Prototype 1",
                width: 2000,
                height: 800,
              },
              {
                src: "/images/projects/elastup/prototypes.svg",
                alt: "Prototype 2",
                width: 2000,
                height: 800,
              },
            ],
            mediasLayout: "full-width",
          },
        ],
      },
      {
        blocks: [
          {
            type: "title",
            text: "Posters of our campaign",
          },
          {
            type: "media",
            medias: [
              {
                src: "/images/projects/elastup/blue-elastup.svg",
                alt: "Poster 1",
                width: 400,
                height: 600,
              },
              {
                src: "/images/projects/elastup/grey-elastup.svg",
                alt: "Poster 2",
                width: 400,
                height: 600,
              },
              {
                src: "/images/projects/elastup/green-elastup.svg",
                alt: "Poster 3",
                width: 400,
                height: 600,
              },
            ],
            mediasLayout: "grid",
          },
        ],
      },
      {
        blocks: [
          {
            type: "title",
            text: "Campaign Video",
            position: "center",
          },
          {
            type: "video",
            media: {
              src: "/videos/projects/elastup/elastup.mp4",
              placeholder: "/images/projects/elastup/play-video.svg",
              width: 800,
              height: 450,
            },
          },
        ],
      },
    ],
  },
  {
    slug: "newfaces",
    hero: {
      title: "NewFaces — Your Fashion Learning Platform",
      subtitle:
        "I designed NewFace a fictionnal user-centric platform to streamline talent discovery for actors, models, and agencies, enhancing profile visibility and engagement through intuitive UX/UI design.",
      carousel: {
        type: "carousel",
        medias: [
          {
            src: "/images/projects/newfaces/home-page-2.svg",
            width: 390,
            height: 844,
          },
          {
            src: "/images/projects/newfaces/courses-page.svg",
            width: 390,
            height: 844,
          },
          {
            src: "/images/projects/newfaces/portfolio.svg",
            width: 390,
            height: 844,
          },
          {
            src: "/images/projects/newfaces/final-page.svg",
            width: 390,
            height: 844,
          },
        ],
      },
    },
    steps: [
      {
        blocks: [
          {
            type: "mix",
            title: "User Research & Insights",
            text: "To understand the needs of actors, models, and agencies, I conducted user interviews, surveys, and competitive analysis. Key pain points emerged around profile discoverability, navigation, and visual clarity.\n- Users struggle to quickly find relevant talent profiles.\n- Mobile navigation is often cumbersome in existing platforms.\n- Agencies need clear indicators of talent availability and experience.",
            media: {
              src: "/images/common/desk.jpg",
              width: 200,
              height: 200,
              alt: "User Research",
            },
            position: "left",
          },
        ],
      },
      {
        blocks: [
          {
            type: "card",
            title: "User Personas",
            text: "Based on the research, I created detailed personas to guide design decisions.",
            cards: [
              {
                model: {
                  src: "/images/common/woman.png",
                },
                name: "Emma",
                role: "Model",
                age: 24,
                text: "**Goals:** Find opportunities and showcase portfolio easily<br>**Pain Points:** Navigation confusion, poor image layout",
              },
              {
                model: {
                  src: "/images/common/man.png",
                },
                name: "Lucas",
                role: "Actor",
                age: 28,
                text: "**Goals:** Get noticed by agencies quickly<br>**Pain Points:** Unclear profile visibility and metrics",
              },
              {
                model: {
                  src: "/images/common/woman.png",
                },
                role: "Agency Manager",
                age: 35,
                text: "**Goals:** Efficiently discover and manage talent<br>**Pain Points:** Difficult filtering and slow loading profiles",
              },
            ],
          },
        ],
      },
      {
        blocks: [
          {
            type: "title",
            text: "Low-Fidelity Prototyping",
            position: "center",
          },
          {
            type: "text",
            text: "To quickly iterate on design concepts, I developed low-fidelity wireframes focusing on layout, navigation, and core functionalities.",
            position: "center",
          },
          {
            type: "media",
            medias: [
              {
                src: "/images/projects/newfaces/proto-1.svg",
                alt: "Wireframe 1",
                width: 390,
                height: 844,
              },
              {
                src: "/images/projects/newfaces/proto-2.svg",
                alt: "Wireframe 2",
                width: 390,
                height: 844,
              },
            ],
            mediasLayout: "grid",
          },
          {
            type: "title",
            text: "High-Fidelity Prototyping",
            position: "center",
          },
          {
            type: "text",
            text: "Interactive prototypes were created to validate flows and test usability before development.",
            position: "center",
          },
          {
            type: "media",
            medias: [
              {
                src: "/images/projects/newfaces/home-page-2.svg",
                width: 390,
                height: 844,
              },
              {
                src: "/images/projects/newfaces/courses-page.svg",
                width: 390,
                height: 844,
              },
              {
                src: "/images/projects/newfaces/portfolio.svg",
                width: 390,
                height: 844,
              },
            ],
            mediasLayout: "grid",
          },
          {
            type: "media",
            medias: [
              {
                src: "/images/projects/newfaces/final-page.svg",
                width: 390,
                height: 844,
              },
            ],
            mediasLayout: "grid",
          },
        ],
      },
      {
        blocks: [
          {
            type: "title",
            text: "Next Steps",
            position: "center",
          },
          {
            type: "text",
            text: "Conduct usability testing with real users, refine micro-interactions, and collaborate with developers to ensure design fidelity during implementation.",
            position: "center",
          },
        ],
      },
    ],
  },
  {
    slug: "ai-fashion",
    hero: {
      title: "AI Fashion Intelligent Styling Experience",
      subtitle:
        "I designed a fictionnal UI/UX IA fashion app that helps people find style recommendations being able to virtually try on clothes and get personalized outfit ideas using artificial intelligence.",
      carousel: {
        type: "carousel",
        medias: [
          {
            src: "/images/projects/ai-fashion/home.svg",
          },
          {
            src: "/images/projects/ai-fashion/calendar.svg",
          },
          {
            src: "/images/projects/ai-fashion/chat.svg",
          },
        ],
      },
    },
    steps: [
      {
        blocks: [
          {
            type: "mix",
            title: "User Research & Insights",
            text: "Through research including surveys and interviews with fashion shoppers, i manage to find some relevant points that could be resolved through my app.\n- Users want personalized outfit suggestions.\n- Fashion professionals struggle to keep their schedules updated.\n- Retailers need smarter ways to showcase products with AI.",
            media: {
              src: "/images/common/desk.jpg",
              width: 200,
              height: 200,
              alt: "AI Fashion research",
            },
            position: "left",
          },
        ],
      },
      {
        blocks: [
          {
            type: "card",
            title: "User Personas",
            text: "Those are fictionnal personas that helped me define user needs and refine AI-powered features.",
            cards: [
              {
                model: {
                  src: "/images/common/woman.png",
                },
                name: "Mia",
                role: "Trend-Seeker",
                age: 22,
                text: "**Goals:** Discover new outfits instantly using AI<br>**Pain Points:** Hard to match clothes with her style",
              },
              {
                model: {
                  src: "/images/common/man.png",
                },
                name: "Daniel",
                role: "Professional model",
                age: 30,
                text: "**Goals:** Being more informed about the fashion world<br>**Pain Points:** Not enough time to stay properly informed",
              },
              {
                model: {
                  src: "/images/common/woman.png",
                },
                role: "Retail Fashion Manager",
                age: 38,
                text: "**Goals:** Improve product visibility and boost customer engagement with AI styling<br>**Pain Points:** Low visibility, low engagement, and high returns",
              },
            ],
          },
        ],
      },
      {
        blocks: [
          {
            type: "title",
            text: "Low-Fidelity Prototyping",
            position: "center",
          },
          {
            type: "text",
            text: "Sketches and wireframes mapping out AI-driven user flows",
            position: "center",
          },
          {
            type: "media",
            medias: [
              {
                src: "/images/projects/ai-fashion/home_proto.svg",
                alt: "Wireframe 1",
                width: 390,
                height: 844,
              },
              {
                src: "/images/projects/ai-fashion/calendar-proto.svg",
                alt: "Wireframe 2",
                width: 390,
                height: 844,
              },
            ],
            mediasLayout: "grid",
          },
          {
            type: "title",
            text: "High-Fidelity Prototyping",
            position: "center",
          },
          {
            type: "text",
            text: "Prototypes showcasing AI features and the different pages of the app",
            position: "center",
          },
          {
            type: "media",
            medias: [
              {
                src: "/images/projects/ai-fashion/home.svg",
                alt: "Home page",
                width: 390,
                height: 844,
              },
              {
                src: "/images/projects/ai-fashion/calendar.svg",
                alt: "Calendar page",
                width: 390,
                height: 844,
              },
              {
                src: "/images/projects/ai-fashion/chat.svg",
                alt: "Chatbot page",
                width: 390,
                height: 844,
              },
            ],
            mediasLayout: "grid",
          },
        ],
      },
      {
        blocks: [
          {
            type: "title",
            text: "Next Steps",
            position: "center",
          },
          {
            type: "text",
            text: "Further user testing to refine AI recommendations and to improve the user flow of the app",
            position: "center",
          },
        ],
      },
    ],
  },
  {
    slug: "teru-bot",
    hero: {
      title: "TeruBot",
      subtitle:
        "Materializing Collective Emotions Through an Embodied Robotic Metaphor",
      background: "/images/projects/teru-bot/terubot-card-1.svg",
    },
    steps: [
      {
        blocks: [
          {
            type: "topic",
            title: "Description of the product",
            text: "TeruBot is a robot-app system that visualizes the emotional atmosphere of shared spaces. It turns collective feelings into a tangible robotic presence. Inspired by Teru Teru Bōzu, it reinterprets “good weather” as emotional well-being. Through simple animations, it displays group emotions in real time. It fosters emotional awareness and connection.",
            topics: [
              "Collective emotion in shared spaces",
              "Community awareness & connection",
              "Social robotics / robot companion",
            ],
          },
          {
            type: "media",
            medias: [
              {
                src: "/images/projects/teru-bot/group.png",
                alt: "Group",
                width: 1440,
                height: 1874,
              },
            ],
            mediasLayout: "full-width",
          },
        ],
      },
      {
        blocks: [
          {
            type: "title",
            text: "How does it work ?",
          },
          {
            type: "media",
            medias: [
              {
                src: "/images/projects/teru-bot/working-process.jpg",
                alt: "Working Process",
                width: 1600,
                height: 1131,
              },
            ],
            mediasLayout: "full-width",
          },
        ],
        substeps: [
          {
            blocks: [
              {
                type: "title",
                text: "1. Hardware",
              },
              {
                type: "text",
                text: "Terubot is powered by a Raspberry Pi running a local language model (Qwen 2.5 - 1.5B) to process voice input and detect emotional cues. A compact webcam and microphone enable presence detection and speech interaction. In parallel, the Gemini API is being explored to improve emotion recognition and speech-to-text capabilities.<br><br>The system uses three ESP32 microcontrollers: two control dynamic eye displays with real-time animated expressions, while a third manages head movements via a PWM driver for smooth, synchronized motion.<br><br>This distributed architecture allows Terubot to translate detected emotions into physical behaviors, combining eye animations and subtle movements. The robot's head was developed through multiple 3D printing iterations to achieve a balance between mechanical reliability and expressive design.",
              },
              {
                type: "media",
                medias: [
                  {
                    src: "/images/projects/teru-bot/teru-head.jpg",
                    alt: "TeruBot Head",
                    width: 1824,
                    height: 2736,
                  },
                  {
                    src: "/images/projects/teru-bot/teru-neck.png",
                    alt: "TeruBot Neck",
                    width: 1824,
                    height: 2736,
                  },
                  {
                    src: "/images/projects/teru-bot/teru-body.png",
                    alt: "TeruBot Body",
                    width: 1824,
                    height: 2736,
                  },
                ],
                mediasLayout: "grid",
              },
              {
                type: "title",
                text: "2. App",
              },
              {
                type: "text",
                text: "The mobile app is the main interaction point, combining emotional check-ins with the visualization of both personal and collective moods. Unlike traditional mood-tracking tools focused on individual reflection, Terubot introduces a shared dimension through the concept of “emotional weather,” encouraging users to engage with how a community feels.<br><br>The app is structured around four core features: a collective mood visualization, a quick daily check-in, a community channel, and a user profile. Emotions are translated into weather states (sunny, cloudy, stormy), making them intuitive, playful, and non-clinical.<br><br>To keep interactions lightweight, the check-in is based on four key dimensions—mood, energy, stress, and social connection—allowing users to quickly express their state without writing. A shared, anonymous community channel complements this by fostering positive interactions and a sense of belonging without social pressure.",
              },
            ],
          },
        ],
      },
      {
        blocks: [
          {
            type: "title",
            text: "First iteration",
          },
          {
            type: "media",
            medias: [
              {
                src: "/images/projects/teru-bot/app-v1.png",
                alt: "App V1",
                width: 626,
                height: 626,
                caption:
                  "Figure 1 shows the first set of app wireframes developed during this iteration.",
              },
            ],
            mediasLayout: "full-width",
          },
        ],
      },
      {
        blocks: [
          {
            type: "title",
            text: "Second iteration",
          },
        ],
        substeps: [
          {
            blocks: [
              {
                type: "title",
                text: "Visual Design Iteration",
              },
              {
                type: "text",
                text: "In the second iteration, we redesigned the app's visual identity to better reflect its emotional purpose. The interface became more expressive and dynamic, with backgrounds adapting in real time to the user's emotional state using warm or cool tones to mirror mood through ambient feedback.<br><br>We also introduced simple data visualizations, allowing users to track their emotional trends over the past week, along with supportive, non-judgmental messages.<br><br>Finally, an onboarding screen was added to clearly introduce the concept of emotional weather and guide new users through the app's core features.",
              },
              {
                type: "media",
                medias: [
                  {
                    src: "/images/projects/teru-bot/app-v2.png",
                    alt: "App V2",
                    width: 908,
                    height: 276,
                    caption:
                      "Figure 2 presents the second iteration mockups, highlighting the updated visual language",
                  },
                ],
                mediasLayout: "full-width",
              },
              {
                type: "title",
                text: "User Study & Evaluation",
              },
              {
                type: "text",
                text: "A user study (N = 8) evaluated the mobile app and robot through Likert-scale questions, observations, and open feedback. Overall, participants reported a positive experience, highlighting the app's clarity, ease of use, and strong comfort with the emotional check-in process. Most expressed willingness to use it regularly, though deeper emotional reflection could be further developed.<br><br>The robot was perceived as intuitive and engaging, with participants especially valuing its contribution to the overall experience. While interpretations of its expressions varied slightly, its physical presence significantly enhanced the system.<br><br>Observations revealed that users naturally attempted to touch the robot, suggesting a strong expectation of tactile interaction. This highlights the importance of embodiment in emotional systems.<br><br>Future iterations will build on this by adding touch interactions and extending the emotional weather metaphor through physical elements like adaptive clothing, reinforcing Terubot as a tangible and expressive emotional companion.",
              },
              {
                type: "media",
                medias: [
                  {
                    src: "/images/projects/teru-bot/welcome.png",
                    alt: "App Welcome page",
                    width: 1206,
                    height: 2622,
                  },
                  {
                    src: "/images/projects/teru-bot/onboarding-home.png",
                    alt: "App Onboarding Home page",
                    width: 1206,
                    height: 2622,
                  },
                  {
                    src: "/images/projects/teru-bot/onboarding-goal.png",
                    alt: "App Onboarding Goal page",
                    width: 1206,
                    height: 2622,
                  },
                ],
                mediasLayout: "grid",
              },
              {
                type: "media",
                medias: [
                  {
                    src: "/images/projects/teru-bot/onboarding-weather.png",
                    alt: "App Onboarding Weather page",
                    width: 1206,
                    height: 2622,
                  },
                  {
                    src: "/images/projects/teru-bot/teru-bot-5.jpg",
                    alt: "TeruBot Closeup",
                    width: 2048,
                    height: 2731,
                  },
                  {
                    src: "/images/projects/teru-bot/onboarding-connect.png",
                    alt: "App Onboarding Connect page",
                    width: 1206,
                    height: 2622,
                  },
                ],
                mediasLayout: "grid",
              },
              {
                type: "media",
                medias: [
                  {
                    src: "/images/projects/teru-bot/garden-rainy.png",
                    alt: "Rainy Garden",
                    width: 1206,
                    height: 2622,
                  },
                  {
                    src: "/images/projects/teru-bot/garden-sunny.png",
                    alt: "Sunny Garden",
                    width: 1206,
                    height: 2622,
                  },
                  {
                    src: "/images/projects/teru-bot/garden-stormy.png",
                    alt: "Stormy Garden",
                    width: 1206,
                    height: 2622,
                  },
                ],
                mediasLayout: "grid",
              },
              {
                type: "media",
                medias: [
                  {
                    src: "/images/projects/teru-bot/features.jpg",
                    alt: "Features",
                    width: 2048,
                    height: 817,
                  },
                ],
                mediasLayout: "full-width",
              },
              {
                type: "media",
                medias: [
                  {
                    src: "/images/projects/teru-bot/teru-bot-custom.jpg",
                    alt: "TeruBot with glasses",
                    width: 2048,
                    height: 2731,
                  },
                ],
                mediasLayout: "grid",
              },
            ],
          },
        ],
      },
      {
        blocks: [
          {
            type: "title",
            text: "Files (source code, 3D models, hardware schematics)",
          },
          {
            type: "text",
            text: "You can find all the files and 3D models on our GitHub: [Teru Corp](https://github.com/Teru-Corp)",
          },
          {
            type: "document",
            src: "/documents/projects/teru-bot/TeruBot_Chi_paper_2026.pdf",
          },
        ],
      },
    ],
  },
  {
    slug: "secret-valentines",
    hero: {
      title: "Secret Valentines",
      subtitle:
        "A modern, digital love letter delivery system for Valentine's Day.",
    },
    steps: [
      {
        blocks: [
          {
            type: "mix",
            title: "About",
            text: "Secret Valentine is an application designed to allow people to express their love and appreciation anonymously to their crush, friends, and loved ones. Think of it as a modern-day pigeon delivering your secret love letters, dressed up in a beautiful rosé, pink, and purple color palette representing the code of love.",
            media: {
              src: "/images/projects/secret-valentines/discover.png",
              alt: "Discover your letters",
              width: 1414,
              height: 2000,
            },
            position: "left",
          },
        ],
      },
      {
        blocks: [
          {
            type: "title",
            text: "Goal & Purpose",
          },
          {
            type: "text",
            text: "Our purpose is to deliver a fun, safe, and engaging way to reveal your secret love. In a world that is overly connected, taking a moment to send an anonymous, thoughtful message brings back the charm of traditional love letters, modernized for today.",
          },
          {
            type: "media",
            medias: [
              {
                src: "/images/projects/secret-valentines/ui.jpg",
                alt: "UI",
                width: 1414,
                height: 1885,
              },
              {
                src: "/images/projects/secret-valentines/secret-valentines.jpg",
                alt: "Secret Valentines",
                width: 1414,
                height: 2000,
              },
              {
                src: "/images/projects/secret-valentines/letter.jpg",
                alt: "Letter",
                width: 731,
                height: 908,
              },
            ],
            mediasLayout: "grid",
          },
        ],
      },
      {
        blocks: [
          {
            type: "title",
            text: "Background & Story",
          },
          {
            type: "text",
            text: "We launched the first version of this app last year, and it was a massive success at our school! However, we became victims of our own success: our free-plan database quickly reached its maximum capacity, forcing us to constantly migrate between different email addresses to keep the service running.\nThis new and improved version is built to be more robust, scalable, and beautifully designed using modern web technologies to handle all the love letters you can send!",
          },
        ],
      },
      {
        blocks: [
          {
            type: "title",
            text: "Artistic Direction",
          },
          {
            type: "text",
            text: "- *Theme:* Saint Valentine's Day.\n- *Color Palette:* Rosé, shades of pink, and deep purples.\n- *Vibe:* Romantic, mysterious, modern, and engaging.",
          },
        ],
      },
      {
        blocks: [
          {
            type: "title",
            text: "Tech Stack & Architecture",
          },
          {
            type: "text",
            text: "Inside the app folder, this project has been reimagined with a modern stack to avoid the database issues from the past:\n- *Frontend:* React + TypeScript, Vite.\n- *Styling:* Tailwind CSS + Radix UI components (for accessible, elegant UI)\n- *Animations:* Framer Motion (for smooth, lovely transitions)\n- *Backend & Database:* Firebase (to support an active user base, ensuring reliable and scalable delivery of anonymous messages)",
          },
        ],
      },
    ],
  },
];
